name: Unit Test

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest

  steps: 
   - uses: actions/checkout@v2
    
   - name: Run Test
     run: |
       cd _testPlan
       g++ code.cpp -o code
       ./code
      
      
